// Generated by WebFx

module webfx.demo.moderngauge.application {

    // Direct dependencies modules
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.lib.medusa;
    requires webfx.platform.shared.scheduler;

    // Exported packages
    exports webfx.demo.moderngauge;

    // Provided services
    provides javafx.application.Application with webfx.demo.moderngauge.ModernGaugeApplication;

}